---
localhost:
   user: 'root'
   password: ''
   hostname: '127.0.0.1'

server:
   a:
      hostname: '127.0.0.1'
      user: 'root'
      password: ''
#   b:
 #     hostname: '127.0.0.1'
  #    user: 'rds'
   #   password: 'gegene'
